"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var caballero_1 = require("./caballero");
var elfo_1 = require("./elfo");
var mago_1 = require("./mago");
var nalian = new caballero_1.Caballero("Balian", 1, 80, 20, 5);
var natoroon = new elfo_1.Elfo("Natoroon", 1, 60, 35, 10);
var tervosh = new mago_1.Mago("Tervosh", 1, 40, 45, 20);
console.log(nalian.obtenerInformacion());
console.log(natoroon.obtenerInformacion());
console.log(tervosh.obtenerInformacion());
nalian.atacar;
nalian.defender(12);
nalian.subirNivel;
natoroon.atacar;
natoroon.defender(12);
natoroon.subirNivel;
tervosh.atacar;
tervosh.defender(12);
tervosh.subirNivel;
